import Head from 'next/head';
import style from '../styles/index.module.css';
import React, { useEffect, useState } from 'react';
import { useRouter } from 'next/router';
import Link from 'next/link';
import HeaderLogin from './layout/headerLogin';
import ItemDisplay from './items';
import { GetServerSideProps } from 'next';

export default function UserLogin(cookieData: any) {
  const router = useRouter();
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [visible, setVisible] = useState(false);
  const [localData, setLocalData] = useState([]);
  const [userId, setUserId] = useState(0);

  // Local Storageから商品データ取得
  useEffect(() => {
    const collection = Object.keys(localStorage).map((key) => {
      let keyJson = JSON.stringify(key);
      return {
        key: JSON.parse(keyJson),
        value: JSON.parse(localStorage.getItem(key) as string),
      };
    });
    setLocalData(collection as any);
  }, []);

  console.log(localData);

  //"ally-supports-cache"などを除外 (Local Storageの中の商品情報以外を削除)
  const filteredData: any = localData.filter((object: any) => {
    return object.key == object.value.itemId;
  });

  console.log(filteredData);

  // ユーザーIDの取得&POST(onSubmitのタイミングで発火)
  const postUserdata = async () => {
    console.log(email);
    console.log(password);

    const res = await fetch(
      `${process.env.NEXT_PUBLIC_PROTEIN_DATA}/users?email=${email}&password=${password}`
    );
    const json = await res.json();
    const id = await json[0].id;
    // console.log(id) id出てくる OK
    return id;
    //　idを返す
  };

  const data = {
    email: email,
    password: password,
  };

  const handler = async (event: any) => {
    event.preventDefault();
    fetch(`${process.env.NEXT_PUBLIC_PROTEIN}/api/login`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(data),
    })
      .then((response) => {
        response.json();
        if (response.status !== 200) {
          setVisible(true);
        } else if (response.status === 200) {
          filteredData.forEach(async (data: any) => {
            data.value.userId = await postUserdata();

            filteredData.forEach((data: any) => {
              fetch(`${process.env.NEXT_PUBLIC_PROTEIN_DATA}/carts`, {
                method: 'POST',
                headers: {
                  'Content-Type': 'application/json',
                },
                body: JSON.stringify(data.value),
              });
            });
          });
          localStorage.clear();
          router.push('/items');
        }
      })
      .then((data) => {
        console.log(data);
      })
      .catch((error) => {
        console.error(error);
      });
  };

  return (
    <div>
      <HeaderLogin />

      <div className={style.all}>
        <Head>
          <title>ログイン</title>
          <meta
            name="description"
            content="Generated by create next app"
          />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={style.main}>
          <hgroup className={style.hgroup}>
            <h1 className={style.h1}>ログイン</h1>
            <Link href="/users/new">
              <h3 className={style.h3}>新規ユーザー登録はこちら</h3>
            </Link>
            <h3
              className={style.login}
              style={{ display: visible ? 'block' : 'none' }}
            >
              ユーザーが見つかりません。もう一度入力してください。
            </h3>
          </hgroup>
          <form
            className={style.form}
            onSubmit={() => {
              handler(event);
            }}
          >
            <div className={style.group}>
              <input
                type="email"
                name="email"
                placeholder="メールアドレス"
                className={style.input}
                onChange={(e) => {
                  setEmail(e.target.value);
                  setVisible(false);
                }}
                required
                autoComplete="off"
              />
              <span className={style.highlight}></span>
              <span className={style.bar}></span>
              <label className={style.label}></label>
            </div>
            <div className={style.group}>
              <input
                type="password"
                name="password"
                id="password_validation"
                placeholder="パスワード&nbsp;(8文字以上16文字以下)"
                className={style.input}
                onChange={(e) => {
                  setPassword(e.target.value);
                  setVisible(false);
                }}
                required
                pattern=".{8,16}"
                title="8文字以上16文字以下"
                autoComplete="off"
              />
              <span className={style.highlight}></span>
              <span className={style.bar}></span>
              <label className={style.label}></label>
            </div>
            <button
              type="submit"
              className={`${style.button} ${style.buttonBlue}`}
            >
              ログイン
              <div
                className={`${style.ripples} ${style.buttonRipples}`}
              >
                <span className={style.ripplesCircle}></span>
              </div>
            </button>
          </form>
        </main>
      </div>
    </div>
  );
}
